/* CREATING TABLES IN MYSQL*/

CREATE DATABASE BANK;
USE BANK;

CREATE TABLE USERS
(
  USER_ID INT,
  ACCOUNT_NUMBER BIGINT UNIQUE NOT NULL,
  USER_NM VARCHAR(50) NOT NULL,
  USER_PHN INT(10) NOT NULL,
  USER_EMLADD VARCHAR(50) NOT NULL,
  USER_ADDR_LN1 VARCHAR(50) NOT NULL,
  USER_ADDR_LN2 VARCHAR(50),
  PRIMARY KEY (USER_ID)
 )
  
  
CREATE TABLE LOAN_DETAILS (
LOAN_ID INT,
USER_ID INT,
LAST_PAYMENT_DATE DATE,
INSTALLMENT DOUBLE,
DATE_PAYABLE_NEXT DATE,
PRIMARY KEY(LOAN_ID),
FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
);


CREATE TABLE CREDIT_CARD_DETAILS
(
CC_ID INT,
CC_NUMBER BIGINT,
USER_ID INT,
MAX_CREDIT DOUBLE,
OUTSTNDNG_BLNCE DOUBLE,
DUE_DATE DATE,
PRIMARY KEY (CC_ID),
FOREIGN KEY USER_ID REFERENCES USERS(USER_ID)
);


/* FOR ANALYSIS */
CREATE TABLE SHARES_DETAILS
(
SHARE_ID VARCHAR(10),
CMPNY_NM varchar(20),
GMT_TMSTMP bigint,
SHR_PRICE DOUBLE
);


COMMIT;

